### Test Server
GET http://localhost:4000/api HTTP/1.1

### Get List Voices
GET http://localhost:4000/api/voices HTTP/1.1

### Get List Teches
GET http://localhost:4000/api/synthesis-techs HTTP/1.1

### Fake
GET http://localhost:4000/api/tts?voice=end2end_stability_option1&input_text=Đây là văn bản. HTTP/1.1